### ISSUE TITLE
Typo in Chapter ER.html

### ISSUE THREAD

**Issue by FeynmanDNA** [simoninireland/introduction-to-epidemics#13]
Hi, i think the equation for `<k>` for ER graph is probably wrong:
![image](https://user-images.githubusercontent.com/26617036/153553546-a7c9ca47-9924-490d-bb22-c1390d9bac90.png)

https://simondobson.org/introduction-to-epidemics/er.html 
I think it should be `<k> = (N-1) * pEdge`

**Comment by NaincyKumariKnoldus** [comment]
Hey @FeynmanDNA I have fixed this and raised a PR for this. Please review this.
Thanks!

**Comment by simoninireland** [comment]
Thank you :-) -- got the text wrong and the code right
