### ISSUE TITLE
Typo in Book Chapter "Compartmental Model

### ISSUE THREAD

**Issue by FeynmanDNA** [simoninireland/introduction-to-epidemics#14]
Hi great book! Just want to point out a minor typo while reading it :)

The typo is "so so" in https://simondobson.org/introduction-to-epidemics/continuous.html#sir-a-compartmented-model-of-disease
> "MSEIR (for diseases with maternally-conferred temporary immunity), so so on in dizzying array"

(migrated over from epydemic repo issue: https://github.com/simoninireland/epydemic/issues/10)

**Comment by simoninireland** [comment]
Thanks! :-)
